apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: chiaretto-app2
    app.kubernetes.io/component: chiaretto-app2
    app.kubernetes.io/instance: chiaretto-app2
  name: chiaretto-https
spec:
  host: "{{ .Values.route }}"
  port:
    targetPort: 8081-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: chiaretto-app2
    weight: 100
  wildcardPolicy: None
